version: '3.8'

services:
  express-backend:
    build: .
    restart: unless-stopped
    ports:
      - "8888:3000"
    env_file:
      - .env  # Load environment variables from the .env file
    volumes:
      - .:/server